name: Renovate Checks
on:
  push:
    branches:
      - "renovate/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          path: branch

      - name: Install Dependencies in Main
        run: (cd main && pnpm install)
      - name: Install Dependencies in Branch
        run: (cd branch && pnpm install)
      - name: Create Snapshot In Main
        run: (cd main && npx tt-cli take-snapshot ./snap.md)
      - name: Copy Snapshot To Branch
        run: cp main/snap.md branch/snap.md
      - name: Compare Snapshot In Branch
        run: (cd branch && npx tt-cli compare-snapshot ./snap.md)
